on:
  schedule:
    # runs every day at 10:00 AM UTC in jan, feb, aug-dec
    - cron:  '0 10 * 1,2,9-12 *'
  workflow_dispatch:
    inputs:
      season_rebuild:
        description: 'Rebuild Season (9999 defaults to latest season). Do multiple seasons comma separated, e.g. 2017,2019,2021'
        required: false
        default: 9999
        type: number
      full_rebuild:
        description: 'Full Rebuild (overwrites above season)'
        required: true
        default: false
        type: boolean

name: update-computed-numbers

jobs:
  setup:
    runs-on: ubuntu-latest
    name: setup
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      FULL_REBUILD: ${{ inputs.full_rebuild || false }}
      SEASON_REBUILD: ${{ inputs.season_rebuild || 9999 }}
    outputs:
      seasons: ${{ steps.query_seasons.outputs.seasons }}
    steps:
      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: nflverse/nflverse-workflows

      - id: query_seasons
        name: Query Seasons
        run: |
          if [ $FULL_REBUILD == true ]
          then
            seasons=$( Rscript -e 'nflverse.workflows::get_season_range(2014)' )
          elif [ $SEASON_REBUILD == 9999 ]
          then
            seasons=$( Rscript -e 'nflverse.workflows::get_current_season()' )
          else
            seasons="[$SEASON_REBUILD]"
          fi
          echo "seasons=$seasons" >> "$GITHUB_OUTPUT"

  update_seasons:
    needs: setup
    name: Update ${{ matrix.season }} Numbers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        season: ${{ fromJson(needs.setup.outputs.seasons) }}
        type: ["season"]
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NFLVERSE_UPDATE_SEASON: ${{ matrix.season }}
      NFLVERSE_UPDATE_TYPE: ${{ matrix.type }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://nflverse.r-universe.dev'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            local::.,
            callr
          extra-packages: |
            nflverse/nflverse-data
            nflverse/nflreadr
            cran/xgboost@1.7.11.1

      - name: Run update script
        run: Rscript -e 'source("data-raw/_save_computed_numbers.R")'

  combine_seasons:
    needs: [setup, update_seasons]
    name: Combine Computed Numbers
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NFLVERSE_UPDATE_TYPE: "combine"
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true
          extra-repositories: 'https://nflverse.r-universe.dev'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            nflverse/nflverse-data
            nflverse/nflreadr

      - name: Run update script
        run: Rscript -e 'source("data-raw/_save_computed_numbers.R")'
